In [2]:
import numpy as np

## ndarray 생성 및 데이터 타입 확인

In [3]:
a = [1,2,3,4,5]
type(a)

list

In [6]:
arr1 = np.array(a, dtype=int)
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array(a, dtype=float)
arr2

array([1., 2., 3., 4., 5.])

In [5]:
arr2.dtype

dtype('float64')

In [7]:
mylist1 = [1, 2, 3, 4]

In [9]:
arr1 = np.array(mylist1)
arr1

array([1, 2, 3, 4])

In [10]:
mylist2 = ([1, 2, 3, 4], [5, 6, 7,8])
mylist2

([1, 2, 3, 4], [5, 6, 7, 8])

In [13]:
arr3=np.array(mylist2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## ndarray shape 확인

In [14]:
arr3.shape

(2, 4)

# 3. array에서의 data 타입

[numpy data type 살펴 보기](https://engineer-mole.tistory.com/85)


array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됨.<br>
타입이 다른 형태 데이터를 넣어서 ndarray 객체를 만들면 어떻게 될까?

In [16]:
mylist = [1, 1.3, 3.14, 12, "joy"]

In [17]:
mylist[1]

1.3

In [18]:
arr = np.array(mylist)
arr

array(['1', '1.3', '3.14', '12', 'joy'], dtype='<U32')

In [20]:
mylist1=[1, 1.2, 2, 2.3]
arr1 = np.array(mylist1)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2 = np.array(mylist1, dtype="float32")
arr2.dtype

dtype('float32')

In [23]:
arr2

array([1. , 1.2, 2. , 2.3], dtype=float32)

In [25]:
# list 속성 값이 일치하지 않으면 error 발생
arr = np.array(mylist, dtype="int")
arr

ValueError: invalid literal for int() with base 10: 'joy'

# 슬라이싱(Slicing)

In [26]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [28]:
arr.shape

(10,)

## 3-1. index 지정하여 indexing(색인)하기
### 1차원 array

In [29]:
arr[0]

10

In [30]:
arr[4]

14

In [32]:
# 인덱스 10의 결과 출력 : 0부터 카운터 되기 때문에 요소 값은 요소값-1
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [33]:
# arr의  0, 5 인덱스 확인
arr[0],arr[5]

(10, 15)

In [34]:
# arr의  -1과 6의 인덱스 확인
arr[-1], arr[6]

(19, 16)

In [35]:
# arr의  -10과 -6의 인덱스 확인
arr[-10], arr[-6]

(10, 14)

In [36]:
arr[-11] # error

IndexError: index -11 is out of bounds for axis 0 with size 10

In [38]:
print(arr[-10]) # 가능
print(arr[-9]) # 가능
print(arr[-8]) # 가능
print(arr[-7]) # 가능
print(arr[-6]) # 가능

10
11
12
13
14


### 2차원 array

In [56]:
# arr2d = np.array([[4, 5, 14, 7, 11, 10],
#                  [1, 2, 3, 4, 5],
#                  [6, 4, 3, 2]]) # error # array 안에 행 값이 다를 경우 error 발생 : The detected shape was (3,) + inhomogeneous part.
arr2d = np.array([[4, 5, 14, 7, 11, 10],
                 [1, 2, 3, 4, 5, 45],
                 [6, 4, 3, 2, 0, 29]])

In [57]:
# arr2d 객체의 shape 확인하기
arr2d.shape

(3, 6)

#### 2차원 ndarray 요소 확인
- 2차원 어레이명[행 인덱스, 열 인덱스]

In [58]:
# 3 행 전체
arr2d[2]

array([ 6,  4,  3,  2,  0, 29])

In [59]:
# 인덱스 (0, 2) 요소
arr2d[0, 2]

14

In [60]:
# 인덱스 (2, 1) 요소
arr2d[2, 1]

4

In [61]:
# arr2d[2, 3], arr2d[0, 2] 확인해 보기
arr2d[2, 3], arr2d[0, 2]

(2, 14)

In [62]:
# 특정 위치에 값 변경
# 인덱스 (2,3)에 값 12->13으로 변경
arr2d[2,3] = 13
arr2d

array([[ 4,  5, 14,  7, 11, 10],
       [ 1,  2,  3,  4,  5, 45],
       [ 6,  4,  3, 13,  0, 29]])

### 3차원 array

In [46]:
arr3d = np.array([[[1, 2,],[3, 4]], 
                  [[5, 6], [7, 8]], 
                  [[9, 10], [11, 12]]])

In [47]:
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [48]:
arr3d.shape

(3, 2, 2)

In [49]:
arr3d1 = np.array([[[1, 2, 3],[3, 4, 5]], 
                  [[5, 6, 0], [7, 8, 9]], 
                  [[9, 10, 10], [11, 12, 20]]])

In [50]:
arr3d1.shape

(3, 2, 3)

In [51]:
print(arr3d1)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  0]
  [ 7  8  9]]

 [[ 9 10 10]
  [11 12 20]]]


### 3-3. 범위 색인
#### 1차원
- arr[start:stop:step]
- arr[::-1] # step이 음수인 경우 거꾸로 출력

In [64]:
arr = np.arange(10,20)

In [65]:
arr2 = [20,40,65,80,30,10,65,55]

In [66]:
print(arr)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]
[20, 40, 65, 80, 30, 10, 65, 55]


In [68]:
print(arr[:-1]) # 마지막 값 직전 값까지 정렬
print(arr[::-1]) # 정렬이 아닌 순서를 가장 뒤에서부터 정렬

[10 11 12 13 14 15 16 17 18]
[19 18 17 16 15 14 13 12 11 10]


In [69]:
# index n부터 끝까지
print(arr[1:])
print(arr[2:])

[11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19]


In [71]:
# 처음 ~ n 까지 n에서 스탑
# [start, stop, step]
print(arr[:5]) # 0:5
print(arr[::6]) # 0:0:6 처음부터 끝까지 6 step
print(arr[:7:2]) # 처음부터 7번 index까지 2 step
print(arr[1::3])

[10 11 12 13 14]
[10 16]
[10 12 14 16]
[11 14 17]


In [74]:
print(arr[:-1]) # 처음 ~ -n : 마지막까지 가장 마지막 값 n번 직전까지
print(arr[:-2]) 
print(arr[::-1]) # 처음부터 마지막까지 거꾸로 정렬
print(arr[:2:-1]) # 처음부터 step만큼 묶어서 index 값 제외 step : -n개 < -: 거꾸로 정렬하여 n: 뒤에서 부터 step만큼
print(arr[:2:-2])

[10 11 12 13 14 15 16 17 18]
[10 11 12 13 14 15 16 17]
[19 18 17 16 15 14 13 12 11 10]
[19 18 17 16 15 14 13]
[19 17 15 13]


In [76]:
# array name[start:stop:step]
print(arr[0:7:1]) # 0 1 2 3 4 5 6 7
print(arr[0:7:2]) # 0 2 4 6

[10 11 12 13 14 15 16]
[10 12 14 16]


In [78]:
print(arr[:6:2], arr[:2:1])
print(arr[:8:3], arr[2:3:2])

[10 12 14] [10 11]
[10 13 16] [12]


#### 2차원
- 2차원 array name[행start(n-1):행stop(n-1), 열start:열stop]

In [63]:
arr2d = np.array([[1, 2, 3, 4, 13, 17], 
                  [4, 5, 14, 7, 11, 10], 
                  [9, 10, 11, 12, 20, 30]])

In [82]:
# 0 row(행)의 값을 모두 슬라싱하기
print(arr2d[0, :]) # 0번째 행, 0:n까지 == :

[ 1  2  3  4 13 17]


In [84]:
# 3 column(열)을 모두 슬라이싱하기
print(arr2d[:, 2]) # 0:n까지 == : , 2번째 열

[ 3 14 11]


In [86]:
# 부분적으로 슬라이싱하기
print(arr2d[:2, :]) # 0:2(1 index)까지, 0:n까지 == :

[[ 1  2  3  4 13 17]
 [ 4  5 14  7 11 10]]


In [94]:
# 부분적으로 슬라이싱하기
print(arr2d[:2, 2:]) # 0:2(1 index)까지, 2:n까지
print(arr2d[:2, 2:4])

[[3 4]
 [7 8]]
[[3 4]
 [7 8]]


##### 문제. 다음과 같이 슬라이싱하기
- 행 : 1~3행까지, 열 : 1부터 모두

In [92]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
print(arr2d[1:, :])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [95]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
print(arr2d[0:2, 1:3])

[[2 3]
 [6 7]]


## 4. Fancy 인덱싱
fancy 인덱싱은 범위가 아닌 **특정 index의 값들을 추출**하고 싶을 때 사용<br>
index list 업하여 적용하면 값을 추출할 수 있음<br>
사용법 : array name[[index list 위치]]

### 4-1. 1차원 fancy 인덱싱

In [96]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [98]:
# index를 list로 정의 해서 값을 추출
arr[[1, 2, 5]] # array name[[추출할 index 값]]

array([23,  2, 65])

In [99]:
# index list를 변수에 대입하여 추출
idx = [1, 2, 5] 
arr[idx]

array([23,  2, 65])

### 4-2. 2차원 fancy
arr2d[[요소1의 행, 요소2의 행], [요소1의 열, 요소2의 열]]

In [100]:
#arr2d[[행index목록],[열index목록]]
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
print(arr2d[:, [1, 3]])

[[ 2  4]
 [ 6  8]
 [10 12]]


In [102]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [105]:
#arr2d[[요소n의 행,요소n의 행],[요소n의 열, 요소n의 열]]
print(arr2d[[1, 2, 0], [1, 2, 1]])

[ 6 11  2]


#### 문제
<pre>
 array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]])
</pre>

In [106]:
arr2d1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [115]:
print(arr2d1[[2, 2], [0, 3]])

[ 9 12]


In [104]:
arr3d1 = np.array([[[1, 2, 3],[3, 4, 5]], 
                  [[5, 6, 0], [7, 8, 9]], 
                  [[9, 10, 10], [11, 12, 20]]])

In [131]:
# print(arr3d1[[[1, 2, 0], [2, 1, 1], [0, 1, 2]]])
# print(arr3d1[[[[0]], [[1]], [[2]]]])
print(arr3d1[[[0], [1], [2]]])

[[[[ 1  2  3]
   [ 3  4  5]]]


 [[[ 5  6  0]
   [ 7  8  9]]]


 [[[ 9 10 10]
   [11 12 20]]]]


## 5. Boolean index(Masking)
조건 필터링을 통하여 Boolean 값으로 색인<br>
True 인값만 추출됨

### 5-1. True와 False 값으로 색인하기

#### 1차원

In [132]:
arr = np.arange(10, 61, 10)
print(arr)

[10 20 30 40 50 60]


In [139]:
TFset = [True, False, True]

In [140]:
# error : 인덱스 갯수 맞춰줘야 함 : 1차원
print(arr[TFset]) # dimension is 6 but corresponding boolean dimension is 3

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 3

In [141]:
TFset2 = [True, False, True, True, False, True]

In [142]:
print(arr[TFset2])

[10 30 40 60]


In [145]:
TFset3 = [True, False, True, False, False, False]
print(arr[TFset3])
TFset4 = [False, True, False, True, False, True]
print(arr[TFset4])

[10 30]
[20 40 60]


#### 2차원

In [146]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [147]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [151]:
# boolean list로 정의, 행단위로 정의
TFset = [True, True, False]
TFset2 = [True, False] # error : 행 갯수가 안 맞으면 오류남

In [149]:
print(arr2d[TFset])

[[1 2 3 4]
 [5 6 7 8]]


In [153]:
TFset1 = [True, True, False]
TFset2 = [False, True, True]

print(arr2d[TFset1], [TFset2])

[[1 2 3 4]
 [5 6 7 8]] [[False, True, True]]


### 조건 필터
비교 연산자를 활용하여 필터를 생성 함
- arr2d[조건필터]

In [154]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [157]:
# ndarray 조건식
# ndarray에 조건식을 주면 boolean 값 반환
print(arr2d > 2)
arr2d > 2

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [158]:
# arr2d[조건필터]
print(arr2d[ arr2d > 2 ])
arr2d[ arr2d > 2 ]

[ 3  4  5  6  7  8  9 10 11 12]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
print(arr2d[ arr2d < 5 ])

[1 2 3 4]


##### [문제] shape (3,2,4) ndarray를 만들고, 조건 필터식 적용하기
- 조건필터 : 11보다 큰값 출력

In [163]:
arr3d = [[[1,2,3,4],
          [5,6,7,8]],
         [[9,10,11,12],
          [13,14,15,4]],
         [[5,6,7,8],
          [9,10,11,12]]]
arr3d = np.array(arr3d)

In [161]:
arr3d.shape

(3, 2, 4)

In [162]:
print(arr3d[arr3d > 11])

[12 13 14 15 12]


In [164]:
arr = np.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [166]:
arr3d = arr.reshape(3,2,4)
print(arr3d[arr3d>11])
print(arr3d)

[12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


* * *

## 2차원 boolindex 부연설명
각 names의 성분(7개 열)에 따라 ---> data의 각 행 대응된다고 생각해 보자.<br>
예를 들어 aaa라는 사람은 1행, bbb는 2행에 대응 된다고 생각하고 아래처럼 array 조건문을 입력해 보자

In [167]:
names = np.array(["aaa", "bbb","ccc", "ddd", "eee", "fff", "ggg"])
data = np.random.rand(7,4)

In [169]:
print(names)
print(data)

['aaa' 'bbb' 'ccc' 'ddd' 'eee' 'fff' 'ggg']
[[0.14205457 0.37937013 0.12396545 0.02544811]
 [0.43511616 0.71061643 0.71134548 0.40969846]
 [0.51964786 0.06051195 0.90331275 0.00266003]
 [0.79943378 0.54664461 0.80244173 0.68663084]
 [0.37326473 0.89640154 0.16326895 0.16175242]
 [0.70404579 0.71870955 0.22278502 0.15033393]
 [0.39626715 0.67675219 0.4739893  0.25789743]]


In [174]:
print(names=="aaa")

[ True False False False False False False]


In [176]:
print(data[names=="aaa", :])

[[0.14205457 0.37937013 0.12396545 0.02544811]]


In [178]:
print(names=="ccc")

[False False  True False False False False]


In [179]:
print(data[names=="ccc", :])

[[0.51964786 0.06051195 0.90331275 0.00266003]]


#### **문제**
- "ggg"에 대응되는 값 추출

In [181]:
print(names=="ggg")
print(data[names=="ggg", :])

[False False False False False False  True]
[[0.39626715 0.67675219 0.4739893  0.25789743]]


In [182]:
nums = np.array([1, 2, 3, 4, 5])
data1 = np.random.rand(5,4)

In [183]:
print(nums)
print(data1)

[1 2 3 4 5]
[[0.10324815 0.28204872 0.24156004 0.77377678]
 [0.54386153 0.43491533 0.33484172 0.86051447]
 [0.09840419 0.0914667  0.43787922 0.57385256]
 [0.33141793 0.66516946 0.58680591 0.2650051 ]
 [0.88994053 0.3340261  0.24792109 0.335258  ]]


In [184]:
print(nums == 1)
print(nums == 2)
print(nums == 3)
print(nums == 4)
print(nums == 5)

[ True False False False False]
[False  True False False False]
[False False  True False False]
[False False False  True False]
[False False False False  True]


In [192]:
# 대응되는 data nama[행, 열]
print(data1[nums==1, 1:3])
print(data1[nums==1, :3])
print(data1[nums==1, :2])
print(data1[nums==2, 1:])
print(data1[nums==3, 2:2])
print(data1[nums==4, 0:2])
print(data1[nums==5, 1:3])
print(data1[nums==4, :])

[[0.28204872 0.24156004]]
[[0.10324815 0.28204872 0.24156004]]
[[0.10324815 0.28204872]]
[[0.43491533 0.33484172 0.86051447]]
[]
[[0.33141793 0.66516946]]
[[0.3340261  0.24792109]]
[[0.33141793 0.66516946 0.58680591 0.2650051 ]]


In [207]:
print(data1[nums==4, :10]) # error는 나지 않음
print(data1[3, 2]) # 변수명 으로 행 index 값을 대체 함

[[0.33141793 0.66516946 0.58680591 0.2650051 ]]
0.5868059069366068


In [209]:
nums2 = np.array([1, 2, 3, 4, 5])
data2 = np.random.rand(len(nums2),4)

In [211]:
print(nums2)
print(data2)

[1 2 3 4 5]
[[0.59873977 0.54844401 0.99946446 0.09348884]
 [0.62014052 0.94303565 0.73474068 0.66644153]
 [0.56741227 0.04790654 0.79605914 0.19499439]
 [0.31808149 0.50012764 0.60409218 0.40421617]
 [0.48327619 0.45664761 0.31596561 0.69391665]]


In [212]:
print(data2[nums2[0], :])

[0.62014052 0.94303565 0.73474068 0.66644153]


In [213]:
nums3 = np.array([1, 2, 3, 4, 5])
data3 = np.random.rand(7, 4)

In [215]:
print(data3[nums3[0], :])

[0.29950895 0.47594463 0.53102285 0.16499243]


In [217]:
print(data3[nums3==1, :]) # error : index 길이가 다를 경우 안에 요소 값으로는 사용가능하나 인덱스 자체로는 사용 불가

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5