# numpy 객체 연산자 살펴보기
- (+, -, *)
- ndarray shape == 서로 동일해야 함
- broadcast : 각 위치를 찾아서 연산이 일어남

## 1. Element-wise operations

numpy는 기본적으로 array 간의 사칙연산을 지원<br>
행과 열이 같은 배열을 계산하면 같은 위치에 있는 값들이 서로 계산됨<br>
이런 현상을 Element-wise operations이라 하며 Shape이 같을 때 발생함.

In [1]:
import numpy as np

### 1-1. 덧셈(+)

In [2]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [3]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [4]:
print(a+b)

[[4 6 8]
 [3 5 7]]


In [5]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [6]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [7]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [8]:
nums = np.arange(1, 7)
print(nums)
a = nums.reshape(-1, 3)

[1 2 3 4 5 6]


In [12]:
nums = np.arange(3, 9)
b = nums.reshape(-1, 3)

In [13]:
print(a.shape)
print(b.shape)
print(a+b)

(2, 3)
(2, 3)
[[ 4  6  8]
 [10 12 14]]


In [41]:
c = nums.reshape(-1, 2)
print(c)

[[3 4]
 [5 6]
 [7 8]]


In [16]:
print(a+c)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### 1-2. Sum - matrix 안에서 sum

In [17]:
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


In [18]:
print(a-b)

[[-2 -2 -2]
 [-2 -2 -2]]


In [19]:
print(a-c)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
print(a * b)

[[ 3  8 15]
 [24 35 48]]


In [21]:
print(a/b)

[[0.33333333 0.5        0.6       ]
 [0.66666667 0.71428571 0.75      ]]


## 2. dot product 사용
- 행렬의 곱셈 연산

### 2-1. dot product
- 내적 : 내적은 두 서열의 상응하는 값들의 곱을 더한 것

In [32]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [23]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [24]:
print(a.shape, b.shape)

(3, 3) (3, 2)


In [25]:
print(np.dot(a, b))

[[22 28]
 [22 28]
 [31 40]]


In [26]:
print(a.dot(b))

[[22 28]
 [22 28]
 [31 40]]


In [27]:
1*1 + 2*3 + 3*5

22

In [28]:
1*2 + 2*4 + 3*6

28

In [29]:
2*1 + 3*3 + 4*5

31

## 3. transpose(전치 행렬)
- 열 -> 행
- 행 -> 열

In [35]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [37]:
a = np.transpose(b)
print(a)

[[1 3 5]
 [2 4 6]]


## 4. Broadcasting

### 4-1. 숫자의 연산(단일)

In [38]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [39]:
print(a+b)
print(a+3)
print(a-3)
print(a*3)
print(a/3)

[[4 5 6]
 [5 6 7]]
[[4 5 6]
 [5 6 7]]
[[-2 -1  0]
 [-1  0  1]]
[[ 3  6  9]
 [ 6  9 12]]
[[0.33333333 0.66666667 1.        ]
 [0.66666667 1.         1.33333333]]


### 4-2. array(배열)의 브로드캐스팅
일정 조건을 부합하는 다른 형태의 배열끼리 연산을 수행하는 것을 의미

1. 맴버가 하나인 배열은 어떤 배열에나 브로드캐스팅(Broadcasting)이 가능(단, 맴버가 하나도 없는 빈 배열을 제외) <br>
ex) 3x4 + 1

2. 하나의 배열의 차원이 1인 경우 브로드캐스팅(Broadcasting)이 가능<br>
ex) 4x4 + 1x4

3. 차원의 짝이 맞을 때 브로드캐스팅(Broadcasting)가능<br>
ex) 3x1 + 1x3

In [49]:
print("a", a)
d = np.array([[1, 2, 3]])
print("d", d)
print("a+d", a+d)
print("a-d", a-d)
print("a*d", a*d)
print("a/d", a/d)

a [[1 2 3]
 [2 3 4]]
d [[1 2 3]]
a+d [[2 4 6]
 [3 5 7]]
a-d [[0 0 0]
 [1 1 1]]
a*d [[ 1  4  9]
 [ 2  6 12]]
a/d [[1.         1.         1.        ]
 [2.         1.5        1.33333333]]


In [63]:
e = np.array([[1, 2, 3],
              [4, 5, 6]])
f = np.array([[9, 8],
              [7, 6],
              [5, 4]])
print(e)
print(f)
print(e.shape, f.shape)
print("e+f", e+f)
print("e-f", e-f)
print("e*f", e*f)
print("e/f", e/f)

[[1 2 3]
 [4 5 6]]
[[9 8]
 [7 6]
 [5 4]]
(2, 3) (3, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [65]:
e = np.array([[1, 2, 3]])
f = np.array([[9],
              [7],
              [5]])
print(e)
print(f)
print(e.shape, f.shape)
print("e+f", e+f)
print("e-f", e-f)
print("e*f", e*f)
print("e/f", e/f)

[[1 2 3]]
[[9]
 [7]
 [5]]
(1, 3) (3, 1)
e+f [[10 11 12]
 [ 8  9 10]
 [ 6  7  8]]
e-f [[-8 -7 -6]
 [-6 -5 -4]
 [-4 -3 -2]]
e*f [[ 9 18 27]
 [ 7 14 21]
 [ 5 10 15]]
e/f [[0.11111111 0.22222222 0.33333333]
 [0.14285714 0.28571429 0.42857143]
 [0.2        0.4        0.6       ]]


#### 브로드 캐스팅 연산 행열 예시
[1x4 + 4x1 행렬 연산 이미지 참고](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fc239jk%2FbtqCM8NKsXw%2FRhz8cdGI7PbE5KM5KX4ag0%2Fimg.png)

In [71]:
value1 = np.array([[1,2,3,4],[2,5,6,7],[8,9,10,11],[12,13,14,15]])
value2 = np.array([1])
value3 = np.array([3,3,3,3])
value4 = np.array([4,5,6,7]).reshape(4,1)

In [72]:
print(value1)
print(value2)
print(value3)
print(value4)

[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[1]
[3 3 3 3]
[[4]
 [5]
 [6]
 [7]]


In [67]:
print(Value + Value1) #4x4 + 1

[[ 2  3  4  5]
 [ 3  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [68]:
print(Value + Value2) #4x4 + 1x4

[[ 4  5  6  7]
 [ 5  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]


In [69]:
print(Value2 + Value3) #1x4 + 4x1

[[ 7  7  7  7]
 [ 8  8  8  8]
 [ 9  9  9  9]
 [10 10 10 10]]


In [70]:
# 4x1 + 1x4
Value3 + Value2

array([[ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10]])

## 특정 값으로 채워넣는 행렬 함수

### 5-1 대각 행렬 함수
**squere matrix (정방 행렬) : 행, 열의 크기 똑같음**
<pre>
np.eye(N, M=None, k=0, dtype=np.int32
np.eye(N, M=None, k=0, dtype=np.float32)

(N x M) 크기의 2차원 행렬을 만들어 주는 함수. k 에 따라 시작위치가 달라짐
</pre>
- N : Row 수 (필수적 요소) 
- M : Column 수(따로 설정하지 않으면 NxN의 정사각행렬이 만들어짐)
- K : 대각행렬이 값을 가지기 시작하는 위치
    - default : 0

In [75]:
# 2 x 2 행렬, 시작위치 0
print(np.eye(N=2))

[[1. 0.]
 [0. 1.]]


In [76]:
# 2 x 3 행렬, 시작위치 0
print(np.eye(N=2, M=3))

[[1. 0. 0.]
 [0. 1. 0.]]


In [77]:
# 7 x 7 행렬, 시작위치 +2
print(np.eye(7, k=2))

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [78]:
# 7 x 7 행렬, 시작위치 -2
print(np.eye(7,k=-2))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [83]:
# 7 x 5 행렬, 시작위치 -2
print(np.eye(7, 5,k=0))
print(np.eye(7, 5,k=-2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [79]:
print(np.eye(3, 3, dtype=np.float32))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [80]:
print(np.eye(3, 3, dtype=np.int32))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 5-2. zero 함수
- np.zeros()
- 행렬을 0으로 초기화 해줌

In [81]:
np.zeros(4)

array([0., 0., 0., 0.])

In [84]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.zeros((4,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 5-3 ones 함수
- np.ones()
- 행렬을 1로 초기화 함

In [87]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [88]:
one = np.ones((3,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
one.dtype

dtype('float64')

In [90]:
type(one.dtype)

numpy.dtype[float64]

In [91]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

## [문제] 범주형 데이터 숫자로 encoding

[단계1]
#### 1. 다음의 범주형 문자 객체를 만들고 소팅하기
- 주방, 폰, 욕실, 거실
#### 2. 문자열 andarry 값을 파라미터로 받아서 숫자로 인코딩하는 함수 정의하고, 실행 결과 출력하기
- 문자를 0~n-1까지 숫자로 변경<br>
<span style="background-color:#F5F5F5"> 거실 : 0, 욕실 : 1, 주방 : 2, 폰 : 3</span><br>

[단계2]
#### 3. 숫자로 변경한 값을 다시 one-hot 인코딩 형태로 바꾸기
<pre>
[[0, 0, 1, 0],
 [0, 0, 0, 1],
 [0, 1, 0, 0],
 [1, 0, 0, 0]]
</pre>

In [92]:
e_lists=np.array(['주방','폰','욕실','거실'])

In [93]:
# e_lists 정렬하기
np.sort(e_lists)

array(['거실', '욕실', '주방', '폰'], dtype='<U2')

#### 2. 문자열을 숫자로 인코딩 하는 함수 만들기

In [104]:
# e_lists의 요소를 0~3까지 숫자로 변환하는 함수 
def label_encoding(e_lists):
    print(e_lists)
    change_lists=[]
    if "거실" in e_lists and "욕실" in e_lists and "주방" in e_lists and "폰" in e_lists:
        change_lists.append([0, 1, 2, 3])
    #     change_lists.append(0)
    # elif :
    #     change_lists.append(1)
    # elif :
    #     change_lists.append(2)
    # elif :
    #     change_lists.append(3)
    return change_lists

In [105]:
# 범주형 문자열을 정수형 숫자로 바꾸기
np.array(label_encoding(e_lists))

['주방' '폰' '욕실' '거실']


array([[0, 1, 2, 3]])

In [106]:
# e_lists의 요소를 0~3까지 숫자로 변환하는 함수 
def label_encoding(e_lists):
    change_lists=[]
    for test in e_lists:
        print(test)
        if "거실" in e_lists:
            change_lists.append

In [107]:
# 범주형 문자열을 정수형 숫자로 바꾸기
np.array(label_encoding(e_lists))

주방
폰
욕실
거실


array(None, dtype=object)

In [114]:
# e_lists의 요소를 0~3까지 숫자로 변환하는 함수 
def label_encoding(e_lists):
    change_lists=[]
    for test in e_lists:
        # print(test)
        if "거실" == test:
            change_lists.append(0)
        elif "욕실" == test:
            change_lists.append(1)
        elif "주방" == test:
            change_lists.append(2)
        elif "폰" == test:
            change_lists.append(3)
    return change_lists

In [116]:
# 범주형 문자열을 정수형 숫자로 바꾸기
enc_val = np.array(label_encoding(e_lists))
print(enc_val)

[2 3 1 0]


In [124]:
# 만들 갯수
print(np.max(enc_val)+1) # 0부터 세기 때문에 +1 필요
print(np.size(enc_val))

4
4


In [122]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [127]:
# 리스트 넣어서 확인
np.eye(4)[[2, 3, 1, 0]].astype(int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [131]:
e_list = np.eye(4)[enc_val].astype(int)
print(e_list)

[[0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]


In [132]:
np.eye(np.size(enc_val))[enc_val].astype(int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

#### 1. np.zeros()로 2차원 배열을 만들고 적용

In [141]:
enc_val = np.array(label_encoding(e_lists))
enc_val

array([2, 3, 1, 0])

In [136]:
one_hot = np.zeros((4, 4))
print(one_hot)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [137]:
np.arange(enc_val.size)

array([0, 1, 2, 3])

In [138]:
one_hot = np.zeros((enc_val.size, enc_val.size))
print(one_hot)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [139]:
one_hot[[np.arange(enc_val.size)], [enc_val]] = 1

In [140]:
one_hot.astype("int8")

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]], dtype=int8)