# pandas

In [3]:
import pandas as pd
import numpy as np

In [2]:
print(pd)

<module 'pandas' from 'C:\\playdata_lab\\data_analysis\\da_venv\\lib\\site-packages\\pandas\\__init__.py'>


In [6]:
nums = np.arange(1, 8)

In [8]:
s = pd.Series(nums)
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32
<class 'pandas.core.series.Series'>


In [9]:
nums=np.arange(1, 21)
nums = nums.reshape((-1, 4))
print(nums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [10]:
df = pd.DataFrame(nums)
print(df)

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


## DataFrame

### 방법1. list

In [11]:
company1 = [['삼성', 2000, '스마트폰'],
           ['현대', 2500, '자동차'],
           ['LG', 3000, '건조기']]

In [12]:
print(pd.DataFrame(company1))

    0     1     2
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


In [13]:
df1 = pd.DataFrame(company1)
print(df1)

    0     1     2
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


### column name

In [16]:
df1.columns = ["기업명", "매출액", "업종"]
print(df1)

  기업명   매출액    업종
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


In [17]:
df2 = pd.DataFrame(company1, columns=["기업명", "매출액", "업종"])
print(df2)

  기업명   매출액    업종
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


### 방법 2. dict로 만들기 - key:value로 정의

In [18]:
company2 = {
            '기업명':['삼성', '현대', 'LG'], 
            '매출액': [2000, 2500, 3000], 
            '업종': ['스마트폰', '자동차', '건조기']
            }

In [19]:
df3 = pd.DataFrame(company2)
print(df3)

  기업명   매출액    업종
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


#### 특정 column으로 index를 지정하기

In [20]:
print(df1)

  기업명   매출액    업종
0  삼성  2000  스마트폰
1  현대  2500   자동차
2  LG  3000   건조기


In [22]:
df1.index = df1['기업명']
print(df1)

    기업명   매출액    업종
기업명                
삼성   삼성  2000  스마트폰
현대   현대  2500   자동차
LG   LG  3000   건조기


#### series : column 1개 확인하기

In [23]:
df1['매출액']

기업명
삼성    2000
현대    2500
LG    3000
Name: 매출액, dtype: int64

In [24]:
type(df1['매출액'])

pandas.core.series.Series

## [문제1] 다음의 정보를 데이터 프레임으로 만들기
<pre>
이름, 포지션, 나이
진, 서브보컬, 28
슈가, 리드래퍼, 28
제이홉, 서브래퍼, 27
RM, 리더, 26
지민, 리드보컬, 25
뷔, 리드댄서, 25
정국, 리드댄서,23
</pre>

In [62]:
datasList = []
head = "이름, 포지션, 나이"
head = head.split(", ")
# # print("data1",data1)
# datasList.append(data1)
# print(datasList)
data1 = "진, 서브보컬, 28"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "슈가, 리드래퍼, 28"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "제이홉, 서브래퍼, 27"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "RM, 리더, 26"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "지민, 리드보컬, 25"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "뷔, 리드댄서, 25"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)
data1 = "정국, 리드댄서, 23"
data1 = data1.split(", ")
datasList.append(data1)
print(datasList)

[['진', '서브보컬', '28']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28'], ['제이홉', '서브래퍼', '27']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28'], ['제이홉', '서브래퍼', '27'], ['RM', '리더', '26']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28'], ['제이홉', '서브래퍼', '27'], ['RM', '리더', '26'], ['지민', '리드보컬', '25']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28'], ['제이홉', '서브래퍼', '27'], ['RM', '리더', '26'], ['지민', '리드보컬', '25'], ['뷔', '리드댄서', '25']]
[['진', '서브보컬', '28'], ['슈가', '리드래퍼', '28'], ['제이홉', '서브래퍼', '27'], ['RM', '리더', '26'], ['지민', '리드보컬', '25'], ['뷔', '리드댄서', '25'], ['정국', '리드댄서', '23']]


In [63]:
df4 = pd.DataFrame(datasList, columns=head)
print(df4)

    이름   포지션  나이
0    진  서브보컬  28
1   슈가  리드래퍼  28
2  제이홉  서브래퍼  27
3   RM    리더  26
4   지민  리드보컬  25
5    뷔  리드댄서  25
6   정국  리드댄서  23


In [72]:
datas2 = """진, 서브보컬, 28
슈가, 리드래퍼, 28
제이홉, 서브래퍼, 27
RM, 리더, 26
지민, 리드보컬, 25
뷔, 리드댄서, 25
정국, 리드댄서, 23"""

datas2 = datas2.replace("\n", ", ").split(", ")
print(datas2)


['진', '서브보컬', '28', '슈가', '리드래퍼', '28', '제이홉', '서브래퍼', '27', 'RM', '리더', '26', '지민', '리드보컬', '25', '뷔', '리드댄서', '25', '정국', '리드댄서', '23']


In [70]:
1num = [0, 3,  
btsDict={}
name = []
position = []
age = []
key = "이름, 포지션, 나이"
key = key.split(", ")



['진']
진
['서브보컬']
서브보컬
['28', '슈가']
28
슈가
['리드래퍼']
리드래퍼
['28', '제이홉']
28
제이홉
['서브래퍼']
서브래퍼
['27', 'RM']
27
RM
['리더']
리더
['26', '지민']
26
지민
['리드보컬']
리드보컬
['25', '뷔']
25
뷔
['리드댄서']
리드댄서
['25', '정국']
25
정국
['리드댄서']
리드댄서
['23']
23


In [61]:
holsu = np.arange(1, 40, 2)
# print(holsu.reshape(-1, 4))
holsu = holsu.reshape(-1, 4)
df5 = pd.DataFrame(holsu)
print(df5)

    0   1   2   3
0   1   3   5   7
1   9  11  13  15
2  17  19  21  23
3  25  27  29  31
4  33  35  37  39
